import React, { useState } from 'react';
import { ShieldCheck, SlidersHorizontal } from 'lucide-react';
import { ADMIN_FEATURES } from '../services/aura-ai';
import AdminBriefing from '../components/ai/AdminBriefing';
import PolicyReview from '../components/ai/PolicyReview';

export default function AdminOperations() {
  const [selected, setSelected] = useState(ADMIN_FEATURES[0].id);
  const tool = ADMIN_FEATURES.find((item) => item.id === selected) || ADMIN_FEATURES[0];
  return <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-7"><section className="rounded-[2rem] border border-emerald-200 bg-white/90 p-8 sm:p-10 shadow-sm"><div className="flex items-start gap-4"><div className="rounded-2xl bg-slate-950 p-3 text-emerald-400"><SlidersHorizontal className="w-6 h-6" /></div><div><div className="inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1 text-xs font-mono text-emerald-950"><ShieldCheck className="w-3.5 h-3.5" /> Public-data operations</div><h1 className="mt-3 text-3xl font-extrabold text-slate-950">Admin operations</h1><p className="mt-2 max-w-3xl text-sm leading-relaxed text-slate-600">Two Gemini-assisted operational tools for the public registry. They do not grant wallet authority, alter a contract, or access private proof material. Put this route behind your organization’s Vercel authentication before production use.</p></div></div></section><section className="grid lg:grid-cols-[.7fr_1.3fr] gap-6"><nav className="rounded-3xl border border-slate-200 bg-white/90 p-3 shadow-sm space-y-1">{ADMIN_FEATURES.map((item) => <button key={item.id} type="button" onClick={() => setSelected(item.id)} className={`w-full rounded-2xl p-4 text-left ${selected === item.id ? 'bg-emerald-700 text-white' : 'text-slate-800 hover:bg-emerald-50'}`}><span className="text-[10px] font-mono uppercase opacity-70">{item.category}</span><span className="mt-1 block text-sm font-semibold">{item.title}</span><span className="mt-1 block text-xs opacity-75">{item.description}</span></button>)}</nav><section className="rounded-3xl border border-emerald-200 bg-white/90 p-7 shadow-sm"><p className="text-xs font-mono uppercase text-emerald-800">Selected admin tool</p><h2 className="mt-1 text-xl font-bold text-slate-900">{tool.title}</h2><p className="mt-2 text-sm text-slate-600">{tool.description}</p>{selected === 'admin_briefing' ? <AdminBriefing /> : selected === 'policy_review' ? <PolicyReview /> : <div className="mt-7 rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-5 py-8 text-center text-sm text-slate-600">The public-data action for this tool is being prepared.</div>}</section></section></div>;
}
