import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { AlertCircle, Check, CheckCircle2, Copy, Cpu, FileCode2, LockKeyhole, Send, ShieldCheck } from 'lucide-react';
import { midnightService } from '../services/midnight';
import { recordFinalizedSurvey } from '../services/survey-registry';

export default function CreateSurvey() {
  const navigate = useNavigate();
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [network, setNetwork] = useState('preview');
  const [threshold, setThreshold] = useState(50);
  const [options, setOptions] = useState(['Option A', 'Option B', 'Option C', 'Option D']);
  const [progress, setProgress] = useState(null);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(null);

  const copy = async (text, key) => {
    await navigator.clipboard.writeText(text);
    setCopied(key);
    window.setTimeout(() => setCopied(null), 1600);
  };

  const deploy = async (event) => {
    event.preventDefault();
    setError(null);
    setProgress({ text: 'Connecting to 1AM…' });
    try {
      midnightService.setNetwork(network);
      const deployment = await midnightService.deploySurvey({ title, threshold, onProgress: setProgress });
      const survey = recordFinalizedSurvey({ ...deployment, title, description, options });
      setResult({ ...deployment, survey });
    } catch (reason) {
      setProgress(null);
      setError(reason.message || 'The on-chain deployment did not complete.');
    }
  };

  if (result) {
    return (
      <div className="relative z-10 max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <section className="p-8 rounded-3xl bg-white border border-emerald-300 shadow-sm text-center space-y-6">
          <div className="w-16 h-16 mx-auto rounded-3xl bg-emerald-100 text-emerald-700 flex items-center justify-center"><CheckCircle2 className="w-8 h-8" /></div>
          <div><h1 className="text-2xl font-bold text-slate-900">Survey deployed and initialized on Midnight</h1><p className="mt-2 text-sm text-slate-600">These are the finalized network identifiers returned by the live 1AM / Midnight.js transaction flow.</p></div>
          <div className="text-left space-y-3 font-mono text-xs">
            {[
              ['Contract address', result.contractAddress, 'address'],
              ['Deployment transaction ID', result.deploymentTxId, 'deployment-id'],
              ['Deployment transaction hash', result.deploymentTxHash, 'deployment-hash'],
              ['Initialization transaction hash', result.initializationTxHash, 'initialization-hash'],
            ].map(([label, value, key]) => <div key={key} className="p-4 rounded-2xl bg-slate-50 border border-slate-200 break-all"><div className="flex justify-between gap-4 text-slate-500 mb-1"><span>{label}</span><button type="button" onClick={() => copy(value, key)} className="inline-flex gap-1 hover:text-emerald-800">{copied === key ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}Copy</button></div><p className="font-semibold text-slate-900">{value}</p></div>)}
          </div>
          <div className="flex flex-wrap justify-center gap-3"><Link to={`/survey/${encodeURIComponent(result.contractAddress)}`} className="px-4 py-2.5 rounded-xl bg-emerald-700 hover:bg-emerald-800 text-white text-sm font-semibold">View live state</Link><button type="button" onClick={() => navigate('/')} className="px-4 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-800 text-sm font-semibold">Dashboard</button></div>
        </section>
      </div>
    );
  }

  return (
    <div className="relative z-10 max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-10 grid lg:grid-cols-[1.2fr_.8fr] gap-7 items-start">
      <form onSubmit={deploy} className="p-7 rounded-3xl bg-white/90 border border-emerald-200 shadow-sm space-y-6">
        <div><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-100 text-emerald-900 text-xs font-mono"><FileCode2 className="w-3.5 h-3.5" /> 1AM-authorized deployment</div><h1 className="mt-4 text-3xl font-extrabold text-slate-900">Deploy a real survey contract</h1><p className="mt-2 text-sm text-slate-600">No address is reserved or generated by AURA. 1AM must approve both the deployment and initialization transactions.</p></div>
        <fieldset className="grid grid-cols-2 gap-3"><legend className="text-xs font-mono uppercase text-slate-600 mb-2">Midnight network</legend>{['preview', 'preprod'].map((item) => <label key={item} className={`p-3 rounded-2xl border cursor-pointer ${network === item ? 'border-emerald-500 bg-emerald-50' : 'border-slate-200 bg-slate-50'}`}><input className="sr-only" type="radio" name="network" value={item} checked={network === item} onChange={() => setNetwork(item)} /><span className="block text-sm font-bold text-slate-900 capitalize">{item}</span><span className="block mt-1 text-[11px] text-slate-600">Must match 1AM</span></label>)}</fieldset>
        <label className="block text-xs font-mono uppercase text-slate-600">Public title commitment<input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Community grant priorities" className="mt-2 w-full px-4 py-3 rounded-xl bg-slate-50 border border-slate-200 text-sm normal-case font-sans focus:outline-none focus:border-emerald-600" /></label>
        <label className="block text-xs font-mono uppercase text-slate-600">Public context (stored in AURA registry, not contract)<textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={3} className="mt-2 w-full px-4 py-3 rounded-xl bg-slate-50 border border-slate-200 text-sm normal-case font-sans focus:outline-none focus:border-emerald-600 resize-none" /></label>
        <label className="block text-xs font-mono uppercase text-slate-600">Eligibility threshold: {threshold}<input type="range" min="1" max="100" value={threshold} onChange={(event) => setThreshold(Number(event.target.value))} className="mt-3 w-full accent-emerald-700" /><span className="block mt-1 normal-case font-sans text-[11px] text-slate-500">The contract proves a private eligibility score is at least this value. A trusted credential issuer is required before voting is enabled.</span></label>
        <div className="space-y-2"><p className="text-xs font-mono uppercase text-slate-600">Option labels (AURA public metadata)</p>{options.map((option, index) => <input key={index} required value={option} maxLength="120" onChange={(event) => setOptions((current) => current.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} className="w-full px-4 py-2.5 rounded-xl bg-slate-50 border border-slate-200 text-sm focus:outline-none focus:border-emerald-600" />)}</div>
        {error && <p role="alert" className="flex gap-2 p-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-800 text-xs"><AlertCircle className="w-4 h-4 shrink-0" />{error}</p>}
        <button disabled={Boolean(progress) || !title.trim()} className="w-full inline-flex items-center justify-center gap-2 py-3.5 rounded-2xl bg-emerald-700 hover:bg-emerald-800 text-white font-semibold text-sm disabled:opacity-50">{progress ? <><Cpu className="w-4 h-4 animate-spin" />{progress.text}</> : <><Send className="w-4 h-4" />Deploy with 1AM</>}</button>
      </form>
      <aside className="p-7 rounded-3xl bg-slate-900 text-slate-100 space-y-5"><LockKeyhole className="w-6 h-6 text-emerald-400" /><h2 className="text-lg font-bold">What deployment reveals</h2><ul className="space-y-3 text-xs leading-relaxed text-slate-300"><li><ShieldCheck className="inline w-3.5 h-3.5 mr-2 text-emerald-400" />Title SHA-256 commitment, selected network, and eligibility threshold are public.</li><li><ShieldCheck className="inline w-3.5 h-3.5 mr-2 text-emerald-400" />No wallet private key, witness score, or proof preimage is sent to AURA.</li><li><ShieldCheck className="inline w-3.5 h-3.5 mr-2 text-emerald-400" />The generated Compact artifacts are served as public ZK material; they contain no user credential.</li></ul></aside>
    </div>
  );
}
