import React from 'react';
import { ExternalLink, LockKeyhole, ShieldCheck } from 'lucide-react';

export default function Credentials() {
  return <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-7">
    <section className="p-8 rounded-3xl bg-white border border-emerald-200 shadow-sm space-y-4"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-100 border border-amber-200 text-amber-950 text-xs font-mono"><LockKeyhole className="w-3.5 h-3.5" />No simulated credentials</div><h1 className="text-3xl font-extrabold text-slate-900">Eligibility credentials</h1><p className="text-sm leading-relaxed text-slate-600">AURA does not issue sample badges, random scores, or self-attested eligibility. A score supplied by the app would let anyone bypass the Compact assertion, so voting stays unavailable until the project connects a trusted credential issuer.</p></section>
    <section className="grid md:grid-cols-2 gap-5"><article className="p-6 rounded-3xl bg-slate-900 text-slate-100 space-y-3"><ShieldCheck className="w-6 h-6 text-emerald-400" /><h2 className="font-bold">Required issuer contract</h2><p className="text-xs text-slate-300 leading-relaxed">The issuer must bind an eligibility assertion to the holder, enforce expiry/revocation, and provide a witness implementation that stays local to the holder/prover. AURA must not receive a raw score.</p></article><article className="p-6 rounded-3xl bg-white border border-slate-200 space-y-3"><h2 className="font-bold text-slate-900">Current Compact boundary</h2><p className="text-xs text-slate-600 leading-relaxed">The included circuit checks <code>eligibility_score() &gt;= threshold</code>. That proves confidentiality of the witness, not its provenance. The product proposal treats issuer attestation as a mandatory release gate.</p><a href="https://github.com/midnightntwrk/midnight-verifiable-credentials" target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-800 hover:underline">Midnight VC reference work <ExternalLink className="w-3.5 h-3.5" /></a></article></section>
  </div>;
}
