import React, { useState } from 'react';
import { FileCheck } from 'lucide-react';
import AiResponse from '../AiResponse';
import { runAuraAi } from '../../services/aura-ai';

export default function CopyReviewer() {
  const [title, setTitle] = useState(''); const [context, setContext] = useState(''); const [options, setOptions] = useState('');
  const [loading, setLoading] = useState(false); const [error, setError] = useState(null); const [result, setResult] = useState('');
  const review = async (event) => { event.preventDefault(); setLoading(true); setError(null); setResult(''); try { setResult((await runAuraAi('copy_review', { title, publicContext: context, optionLabels: options.split('\n').map((item) => item.trim()).filter(Boolean) })).text); } catch (reason) { setError(reason.message || 'Unable to review this public copy.'); } setLoading(false); };
  return <form onSubmit={review} className="mt-7 space-y-4"><p className="text-xs text-slate-600">Review public survey copy before it becomes metadata. This is a writing review—not legal, accessibility, or policy approval.</p><label className="block text-xs font-mono uppercase text-slate-600">Public title<input required value={title} onChange={(event) => setTitle(event.target.value)} maxLength={180} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm normal-case font-sans focus:border-emerald-600 focus:outline-none" /></label><label className="block text-xs font-mono uppercase text-slate-600">Public context<textarea required value={context} onChange={(event) => setContext(event.target.value)} maxLength={1800} rows={4} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm normal-case font-sans focus:border-emerald-600 focus:outline-none" /></label><label className="block text-xs font-mono uppercase text-slate-600">Option labels <span className="normal-case text-slate-400">(one per line)</span><textarea required value={options} onChange={(event) => setOptions(event.target.value)} maxLength={800} rows={4} placeholder={'Option A\nOption B\nOption C\nOption D'} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm normal-case font-sans focus:border-emerald-600 focus:outline-none" /></label><button disabled={loading || !title.trim() || !context.trim() || !options.trim()} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-800 disabled:opacity-50"><FileCheck className="w-4 h-4" />Review public copy</button><AiResponse loading={loading} error={error} result={result} emptyMessage="Add draft public copy for a clarity and inclusion review." /></form>;
}
