import React, { useState } from 'react';
import { Send } from 'lucide-react';
import AiResponse from '../AiResponse';
import { runAuraAi } from '../../services/aura-ai';

export default function DeploymentCoach() {
  const [title, setTitle] = useState(''); const [network, setNetwork] = useState('preview'); const [threshold, setThreshold] = useState(50); const [options, setOptions] = useState('');
  const [loading, setLoading] = useState(false); const [error, setError] = useState(null); const [result, setResult] = useState('');
  const review = async (event) => { event.preventDefault(); setLoading(true); setError(null); setResult(''); try { setResult((await runAuraAi('deployment_coach', { title, network, eligibilityThreshold: Number(threshold), optionLabels: options.split('\n').map((item) => item.trim()).filter(Boolean), transactionStatus: 'Not started. This is a preflight review only.' })).text); } catch (reason) { setError(reason.message || 'Unable to prepare a deployment review.'); } setLoading(false); };
  return <form onSubmit={review} className="mt-7 space-y-4"><p className="text-xs text-slate-600">This is a public-form preflight. It cannot estimate final wallet fees, access a balance, deploy a contract, or replace 1AM approval.</p><div className="grid sm:grid-cols-2 gap-4"><label className="block text-xs font-mono uppercase text-slate-600">Network<select value={network} onChange={(event) => setNetwork(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm normal-case font-sans"><option value="preview">Preview</option><option value="preprod">Preprod</option></select></label><label className="block text-xs font-mono uppercase text-slate-600">Eligibility threshold<input type="number" min="1" max="100" value={threshold} onChange={(event) => setThreshold(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm normal-case font-sans" /></label></div><label className="block text-xs font-mono uppercase text-slate-600">Public title<input required value={title} onChange={(event) => setTitle(event.target.value)} maxLength={180} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm normal-case font-sans" /></label><label className="block text-xs font-mono uppercase text-slate-600">Public options <span className="normal-case text-slate-400">(one per line)</span><textarea required value={options} onChange={(event) => setOptions(event.target.value)} maxLength={800} rows={4} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm normal-case font-sans" /></label><button disabled={loading || !title.trim() || !options.trim()} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-800 disabled:opacity-50"><Send className="w-4 h-4" />Review deployment readiness</button><AiResponse loading={loading} error={error} result={result} emptyMessage="Add public deployment details for a non-transactional readiness check." /></form>;
}
