import React, { useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import AiResponse from '../AiResponse';
import { runAuraAi } from '../../services/aura-ai';

export default function PolicyReview() {
  const [copy, setCopy] = useState(''); const [audience, setAudience] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(null); const [result, setResult] = useState('');
  const review = async (event) => { event.preventDefault(); setLoading(true); setError(null); setResult(''); try { setResult((await runAuraAi('policy_review', { proposedPublicCopy: copy, intendedAudience: audience, requiredPrivacyClaim: 'Eligibility score is private in a Compact witness; the ballot option is disclosed for a public tally.' })).text); } catch (reason) { setError(reason.message || 'Unable to review the publication policy.'); } setLoading(false); };
  return <form onSubmit={review} className="mt-7 space-y-4"><p className="text-xs text-slate-600">Use this before publishing visible copy. It provides a policy-oriented writing review; your organization remains responsible for final approval.</p><label className="block text-xs font-mono uppercase text-slate-600">Intended audience<input required value={audience} onChange={(event) => setAudience(event.target.value)} maxLength={400} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm normal-case font-sans" /></label><label className="block text-xs font-mono uppercase text-slate-600">Proposed public survey copy<textarea required value={copy} onChange={(event) => setCopy(event.target.value)} maxLength={3500} rows={7} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm normal-case font-sans" /></label><button disabled={loading || !copy.trim() || !audience.trim()} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-800 disabled:opacity-50"><ShieldCheck className="w-4 h-4" />Review publication copy</button><AiResponse loading={loading} error={error} result={result} emptyMessage="Add proposed public copy for an operational policy review." /></form>;
}
